{
  "formatVersion": "1.1",
  "component": {
    "group": "org.composed",
    "module": "composed",
    "version": "1.0.1-21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "composed-1.0.1-21.jar",
          "url": "composed-1.0.1-21.jar",
          "size": 6831,
          "sha512": "469be0a23a4685b57be9224502056e047079c7d1b49a72b0685096320b2b4b0601e1a64f671fe4baa70dceec17ef83ae796aa64affbef53a3ae1c4cb2e8d290a",
          "sha256": "278fe55d4d13486f77f2aeac5fc87822db50c734e6aa104718f792cb523de5ed",
          "sha1": "66fed65766d170abde964e8de05600f9c63e22ba",
          "md5": "d5eab49f91318d0febda3a7850c31701"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "composed-1.0.1-21.jar",
          "url": "composed-1.0.1-21.jar",
          "size": 6831,
          "sha512": "469be0a23a4685b57be9224502056e047079c7d1b49a72b0685096320b2b4b0601e1a64f671fe4baa70dceec17ef83ae796aa64affbef53a3ae1c4cb2e8d290a",
          "sha256": "278fe55d4d13486f77f2aeac5fc87822db50c734e6aa104718f792cb523de5ed",
          "sha1": "66fed65766d170abde964e8de05600f9c63e22ba",
          "md5": "d5eab49f91318d0febda3a7850c31701"
        }
      ]
    }
  ]
}
