{
  "formatVersion": "1.1",
  "component": {
    "group": "org.composed",
    "module": "composed",
    "version": "1.0.1-214",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "composed-1.0.1-214.jar",
          "url": "composed-1.0.1-214.jar",
          "size": 6859,
          "sha512": "ee5ef34e88de9c80c52a5a7392b41e316f348f858e48ed6eaf00350489135cfd3ab973512e5d3a72d408b698b2b6d674835fa2267b7b5205fc15813acc642834",
          "sha256": "bbc77db2167aa840557682befbcc68dbadce76d059d9440883a755f3ea6c776f",
          "sha1": "6239602e920a1139c24019372a42423a3c44f74f",
          "md5": "65416b5026039da09662c50628aeac04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "composed-1.0.1-214.jar",
          "url": "composed-1.0.1-214.jar",
          "size": 6859,
          "sha512": "ee5ef34e88de9c80c52a5a7392b41e316f348f858e48ed6eaf00350489135cfd3ab973512e5d3a72d408b698b2b6d674835fa2267b7b5205fc15813acc642834",
          "sha256": "bbc77db2167aa840557682befbcc68dbadce76d059d9440883a755f3ea6c776f",
          "sha1": "6239602e920a1139c24019372a42423a3c44f74f",
          "md5": "65416b5026039da09662c50628aeac04"
        }
      ]
    }
  ]
}
